name: WZXY_DailyReport

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

  schedule:
  # Github Action 使用世界标准时间（UTC），北京时间（UTC+8）转换为世界标准时需要减去8小时
    - cron:  '01 22,06 * * *' # 默认在每天 UTC 23:30 （北京时间 7:30）执行

jobs:
  USER_01:
    runs-on: ubuntu-latest
    environment: WZXY_CONFIG_01 # 填写需要使用的用户配置对应的环境,请自行根据实际情况修改
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v3
      with:
        path: .cache
        key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
        restore-keys: ${{ secrets.CACHE_NAME }}-
    - name: Run script
      env:
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
        SCT_KEY: ${{secrets.SCT_KEY}}
        GOBOT_URL: ${{secrets.GOBOT_URL}}
        GOBOT_QQ: ${{secrets.GOBOT_QQ}}
        GOBOT_TOKEN: ${{secrets.GOBOT_TOKEN}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        MIAO_CODE: ${{secrets.MIAO_CODE}}
        TG_TOKEN: ${{secrets.TG_TOKEN}}
        TG_CHATID: ${{secrets.TG_CHATID}}
        WZXY_USERNAME: ${{secrets.USERNAME}}
        WZXY_PASSWORD: ${{secrets.PASSWORD}}
        WZXY_CITY: ${{secrets.CITY}}
        ADDRESS_RECOMMEND: ${{secrets.RECOMMEND}}
      run: python wzxy-dailyreport.py

  ## 多账户配置示例，请复制下面的代码后取消注释再修改，粘贴时注意缩进
  # USER_02:
  #   runs-on: ubuntu-latest
  #   environment: WZXY_CONFIG_02 # 填写需要使用的用户配置对应的环境,请自行根据实际情况修改
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python 3.9
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: 3.9
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #   - name: Import cache
  #     uses: actions/cache@v3
  #     with:
  #       path: .cache
  #       key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
  #       restore-keys: ${{ secrets.CACHE_NAME }}-
  #   - name: Run script
  #     env:
  #       DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
  #       DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
  #       SCT_KEY: ${{secrets.SCT_KEY}}
  #       GOBOT_URL: ${{secrets.GOBOT_URL}}
  #       GOBOT_QQ: ${{secrets.GOBOT_QQ}}
  #       GOBOT_TOKEN: ${{secrets.GOBOT_TOKEN}}
  #       BARK_TOKEN: ${{secrets.BARK_TOKEN}}
  #       PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
  #       MIAO_CODE: ${{secrets.MIAO_CODE}}
  #       TG_TOKEN: ${{secrets.TG_TOKEN}}
  #       TG_CHATID: ${{secrets.TG_CHATID}}
  #       WZXY_USERNAME: ${{secrets.USERNAME}}
  #       WZXY_PASSWORD: ${{secrets.PASSWORD}}
  #       WZXY_CITY: ${{secrets.CITY}}
  #       ADDRESS_RECOMMEND: ${{secrets.RECOMMEND}}
  #     run: python wzxy-dailyreport.py
